services:
  waiters-counter-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waiters-counter-backend
    ports:
      - "5551:5551"
    environment:
      - NODE_ENV=production

  waiters-counter-frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: waiters-counter-frontend
    ports:
      - "5552:80"
